[package]
name = "oxidemq-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "oxidemq"
path = "src/main.rs"



[dependencies]
oxidemq-core = { workspace = true }
oxidemq-wal = { workspace = true }
oxidemq-s3stream = { workspace = true }
oxidemq-protocol = { workspace = true }
oxidemq-broker = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio-rustls = { workspace = true }
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
rustls-pemfile = { workspace = true }
rcgen = { workspace = true }
anyhow = { workspace = true }
