[package]
name = "oxidemq-wal"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
oxidemq-core = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
crossbeam-channel = { workspace = true }
parking_lot = { workspace = true }
crc32fast = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
