[package]
name = "oxidemq-compat-tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
oxidemq-core = { workspace = true }
oxidemq-wal = { workspace = true }
oxidemq-s3stream = { workspace = true }
oxidemq-protocol = { workspace = true }
oxidemq-broker = { workspace = true }
oxidemq-server = { workspace = true }
tokio = { workspace = true }
bytes = { workspace = true }
axum = { workspace = true }
serde_json = { workspace = true }



[dev-dependencies]
tempfile = { workspace = true }
